// Generated by webpack
// and exposes the Tailwind CSS correctly
__webpack_require__.r(__webpack_exports__);
// Your app specific Tailwind CSS module goes here
__webpack_require__.p = "http://localhost:3000/";
